server:
  port: 32600
spring:
  security:
    user:
      name: demo
      password: demo
      roles:
        - ROLE_ADMIN
        - ROLE_USER
logging:
  level:
    org.springframework.security: debug