logging:
  level:
    root: info
server:
  port: 33003
  tomcat:
    accept-count: 50
  shutdown: graceful
  servlet:
    context-path: /lowcode
spring:
  datasource:
    driverClassName: "${SPRING_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}"
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/base?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia%2FShanghai"
    username: "${USER_NAME:notebook}"
    password: "${DB_PWD:notebook}"
    hikari:
      maximumPoolSize: "${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:16}"
  main:
    banner-mode: off
  messages:
    basename: i18n/messages
    encoding: utf-8

