spring:
  aop:
    proxy-target-class: false
    auto: false
  servlet:
    multipart:
      max-file-size: 31457280
  mvc:
    async:
      request-timeout: 3600000
  main:
    lazy-initialization: true
  application:
    admin:
      enabled: true #/actuator场景，单独使用没有效果
server:
  port: 32011

demo:
  id: 111
  name: happpppppppy
