###
GET http://localhost:32050/validation/get/null?name=

###
GET http://localhost:32050/validation/get/6666667?name=
###
DELETE http://localhost:32050/validation/del/6666667?name=


###
POST http://localhost:32050/validation/validatedCustom/6666667
Content-Type: application/json

{}
###
POST http://localhost:32050/validation/validatedCustom/666666
Content-Type: application/json

{}
###
POST http://localhost:32050/validation/validatedCustom/666666
Content-Type: application/json

{
  "id": 29,
  "matchEventName": "aaa",
  "dicCountryId": 22,
  "countryName": "sss",
  "dicProvinceId": 55,
  "provinceName": "zhejiang",
  "dicCityId": 999,
  "cityName": "hangzhou"
}

###
GET http://localhost:32050/exception2/nest/2
